### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by jcavat** [jcavat/rust-lp-modeler#15]
@tvincent2 hi, I will add your name on the contributors list for Cargo and in the Readme.md. Do you prefer I put your name or your pseudo ?

**Comment by tvincent2** [comment]
Hi,

Please use my name.

Thanks a lot!

Thomas

**Comment by jcavat** [comment]
@aphi same question for you. What do you prefer ?

**Comment by aphi** [comment]
Submitted a PR for this. Thank you.
