### ISSUE TITLE
Parsing of infeasible CBC solution fails

### ISSUE THREAD

**Issue by zappolowski** [jcavat/rust-lp-modeler#27]
When having a (toy) model like

```
minimize
  obj: a + b
subject to
  c1: a + b <= 1
  c2: a + b >= 2
binaries
  a b
end
```

the resulting solution file looks like

```
Infeasible - objective value 2.00000000
**       0 a                      2                       0
      1 b                      0                       0
```

As the first line is additionally marked with leading '**' parsing fails, as the total number of fields isn't 4 anymore. Thus, an error is returned ("Incorrect solution format") although it could be parsed by simply ignoring the first field (the status itself should be sufficient to mark the result as being potentially unusable).

**Comment by jcavat** [comment]
Thanks for your fix !
