### ISSUE TITLE
Wrong parameters in Cbc command

### ISSUE THREAD

**Issue by tvincent2** [jcavat/rust-lp-modeler#3]
Hello,

Commit b0a9ee1bbf6 changed the command used to run Cbc from `cbc test.lp solve solution sol.sol`(see https://github.com/jcavat/rust-lp-modeler/commit/b0a9ee1bbf6ee784b19b88db2434c2a165791d2e#diff-9088e7468441431402cc8f4e47955a14L113) to `cbc ResultFile=sol.sol test.lp` (see https://github.com/jcavat/rust-lp-modeler/commit/b0a9ee1bbf6ee784b19b88db2434c2a165791d2e#diff-9088e7468441431402cc8f4e47955a14R192).

While cbc executes the former properly, it fails to run the latter (maybe ResultFile is specific to Gurobi?).

I believe this specific command should then be reverted to its previous version.

Let me know if you want me to send a PR.

Thomas

**Comment by jcavat** [comment]
Hello. Of course,  you can sen a PR. I cannot be very useful for now. I am back the 7th of August and I will check these in details. Thanks a lot!
