### ISSUE TITLE
Derive Eq, Hash etc. for variables

### ISSUE THREAD

**Issue by remysucre** [jcavat/rust-lp-modeler#34]
It's common to map objects to variables, like in the Assignment Problem example. Sometimes one would also like to map a variable back to the object, like the BiMap [here](https://github.com/wormhole-optimization/warp/blob/00339a09a728b9a78c123963523e5822e7be9c73/src/lib.rs#L486). For example, the user might want to look for the object associated with a variable once a solution is found. This inverse mapping would require variables like `LpBinary` to implement `Eq` and `Hash`.

**Comment by jcavat** [comment]
A solution for #35 would fix this one ?

**Comment by remysucre** [comment]
> A solution for #35 would fix this one ?

Agreed!
