### ISSUE TITLE
`run` function from solver return a Solution `struct`

### ISSUE THREAD

**Issue by jcavat** [jcavat/rust-lp-modeler#39]
This would change the dsl API 

from:
```
let (solver_status, values) = solver::run(&prob).unwrap();
```
to:
```
let solution = solver::run(&prob).unwrap();
```

- [x] status and hashmap values are parts of the Solution `struct`
- [x] Solution should refer to a problem (with constraints and objective)
- [x] a `eval` function can be call to eval the overall objective function of the problem

**Comment by jcavat** [comment]
6d97ca8 close this issue

**Comment by zappolowski** [comment]
The implementation of your parsing rules (e.g. on [this line](https://github.com/jcavat/rust-lp-modeler/commit/6d97ca8c58e87cdcaca5f03d52e9f6fec4f16e58#diff-5708b621a38a1d3e98fe9eb4966c5edeR40)) will fail if the variable isn't found in the `HashMap`. So, you seem to assume, that all variables are always present in the output. Unfortunately, this isn't always true as e.g. CBC just puts nonzero values in the results file (if there are more than a certain number of variables).

E.g. [this input](https://gist.github.com/zappolowski/1a6fcb9460aa39e279e0d1c398258101) yields an output which looks like:
```
Optimal (within gap tolerance) - objective value -4186.00000000
      3 d3_v10                 1                    -724
      7 d3_v19                 1                    -521
     16 d3_v08                 1                    -172
     19 d3_v13                 1                    -149
     20 d3_v04                 1                    -141
     21 d3_v05                 2                    -140
     32 d1_v02                 1                    -334
     33 d1_v01                 1                    -323
     36 d1_v03                 2                    -288
     39 d1_v22                 2                    -162
     40 d1_v17                 2                    -154
     54 d2_v02                 1                    -334
```

**Comment by jcavat** [comment]
Good point ! 7d59fff should fix this

**Comment by jcavat** [comment]
66a904b close second step of this issue

**Comment by jcavat** [comment]
`eval` should be used with caution. Need to add more test for this new feature.
