### ISSUE TITLE
lp-sum panics on empty vector

### ISSUE THREAD

**Issue by remysucre** [jcavat/rust-lp-modeler#41]
When calling `sum` on an empty vector, I got the panic from here: 

https://github.com/jcavat/rust-lp-modeler/blob/ca7a3cd6ac30ed715a900c5049bc320f6328ad1d/src/dsl/variables.rs#L451

why can't we return 0 when the vector is empty?

**Comment by jcavat** [comment]
You are absolutely right ! I need to fix this
