### ISSUE TITLE
Cbc cannot process generated LP file

### ISSUE THREAD

**Issue by tvincent2** [jcavat/rust-lp-modeler#5]
Hello,

Using the LP file generated in main.rs, Cbc (2.8.14 from Debian Stretch) produces a solution where all variables and the objective value are equal to 0 (see [sol.txt](https://github.com/jcavat/rust-lp-modeler/files/1178194/sol.txt)).

During the solution, Cbc complains about invalid row names:

    Coin3007W ### CoinLpIO::is_invalid_name(): Name is empty
    Coin3007W ### CoinLpIO::are_invalid_names(): Invalid name: vnames[3]: (null)
    Coin3007W ### CoinLpIO::setLpDataRowAndColNames(): Invalid row names

In fact, in the LP file, the objective function is defined by:

    Maximize
      10 a + 20 b

but Cbc apparently expects the objective function to have a name (which should normally be optional).

Adding a name:

    Maximize
      obj: 10 a + 20 b

fixes the issue and allows Cbc to process the file and solve the problem correctly.

I believe a default name should be added to the objective function as it would fix this issue with Cbc and should be harmless for other solvers. Moreover, [it is apparently what is done in Pulp](https://github.com/coin-or/pulp/blob/master/src/pulp/pulp.py#L1521). If it's ok for you, expect a PR soon. :)

Best regards,
Thomas

**Comment by jcavat** [comment]
I am not sure but I think that Pulp add a name for constraints, too. I am pretty sure the default names wasn't mandatory with my version. But if it fixes the problem for Cbc then we should to do it.
Let me know, 
Joël

**Comment by jcavat** [comment]
I tested with my version (2.8) and it works. Are you sure about your version ? I didn't find any 2.8.14 version. What's the error message if you just execute CBC on the lp file ?
```
cbc test.lp
```

I will update CBC with the version 2.9 to have a look. In any case, if it works with this optional name that's fine!

**Comment by tvincent2** [comment]
My bad, it was 2.8.12!

Executing Cbc from the command line gives this:

```
$ cbc test.lp
Welcome to the CBC MILP Solver 
Version: 2.8.12 
Build Date: Sep  3 2014 

command line - cbc test.lp (default strategy 1)
Coin0009I  CoinLpIO::readLp(): Maximization problem reformulated as minimization
Coin3007W ### CoinLpIO::is_invalid_name(): Name is empty
Coin3007W ### CoinLpIO::are_invalid_names(): Invalid name: vnames[3]: (null)
Coin3007W ### CoinLpIO::setLpDataRowAndColNames(): Invalid row names
Use getPreviousNames() to get the old row names.
Now using default row names.
Continuous objective value is 0 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 0 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                0.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.01

Total time (CPU seconds):       0.00   (Wallclock seconds):       0.02
```

Apparently, the missing name for the objective function makes my version of Cbc not load the problem at all (`0 rows, 0 columns (0 integer) and 0 elements`).

Anyway, thanks for accepting my PR!

**Comment by jcavat** [comment]
It's curious. But your PR is certainly more portable. It will be useful if we are faced to the same problem later. Thanks
