### ISSUE TITLE
0.5 release

### ISSUE THREAD

**Issue by EdorianDark** [jcavat/rust-lp-modeler#53]
What is missing for the 0.5 release?
- [x]  Adding new features to change log
. [ ]  Is there enough documentation for native backed?

**Comment by carrascomj** [comment]
Right now, [`NativeCbcSolver`](https://github.com/jcavat/rust-lp-modeler/blob/master/src/solvers/native_cbc.rs#L11) does not provide more functionality than any other backend, although that may (should) not be the case. I hope it will get extended to account things like https://github.com/jcavat/rust-lp-modeler/issues/45#issuecomment-632185150. For that reason, it currently has the same in-code documentation as the other solvers.

With that said, I believe that some documentation for the installation of coin-or cbc could be added like
```shell
# Debian
sudo apt install coinor-cbc
# Arch
sudo pacman -S coin-or
# Mac OS
brew tap coin-or-tools/coinor && brew install coin-or-tools/coinor/cbc
```
What are your thoughts on the documentation? Maybe adding a example?

**Comment by jcavat** [comment]
More time :-) 
Mainly I would like to

- [ ] review #48 and merge it for the next release
- [ ] enhance your contributions & change log in the README.md

(the health situation in my contry has a big impact on my work right now)

**Comment by jcavat** [comment]
The documentation need to be improved. For simplicity we can add a repository in the `examples` folder with a specific `README.md` for `NativeCbcSolver`. 
If we wish to be more professional, we can imagine to generate a static doc with the possibility to run code directly on the navigator (such as https://doc.rust-lang.org/stable/rust-by-example/)

**Comment by dlaehnemann** [comment]
> With that said, I believe that some documentation for the installation of coin-or cbc could be added like
> 
> ```shell
> # Debian
> sudo apt install coinor-cbc
> # Arch
> sudo pacman -S coin-or
> # Mac OS
> brew tap coin-or-tools/coinor && brew install coin-or-tools/coinor/cbc
> ```
> 
> What are your thoughts on the documentation? Maybe adding a example?

For installation of solvers to use with lp-modeler, I have had good experience with using [conda](https://docs.conda.io/en/latest/), which is a very [easily installable package manager](https://conda.io/projects/conda/en/latest/user-guide/install/index.html) that does not need admin rights. The open source solvers that lp-modeler can interface with are available on [conda-forge](https://conda-forge.org/), the community channel:
* `conda create -n coin-or-cbc -c conda-forge coin-or-cbc`: https://github.com/conda-forge/coin-or-cbc-feedstock
* `conda create -n glpk -c conda-forge glpk`: https://github.com/conda-forge/glpk-feedstock

And even [Gurobi can be installed via conda](https://www.gurobi.com/gurobi-and-anaconda-for-windows/) (although with manual addition of a license afterwards):
* `conda create -n gurobi -c gurobi gurobi`

Let me know if there is a PR to contribute respective text to.

**Comment by jcavat** [comment]
yes, you can propose a PR to update REAME.md file with this new documentation

**Comment by dlaehnemann** [comment]
I did, it's in PR #75. As this issue was originally about getting to release 0.5.0, I also included an update to the changelog with all the important changes I could identify from the commits.

**Comment by jcavat** [comment]
Many thanks!
