### ISSUE TITLE
NativeCbcSolver failing

### ISSUE THREAD

**Issue by carrascomj** [jcavat/rust-lp-modeler#55]
Just to document some comments in other issues/PRs that were closed, the `NativeCbcSolver` builds the wrong problem for some formulations.

The problem should be in the [`var_lit`](https://github.com/jcavat/rust-lp-modeler/blob/master/src/solvers/native_cbc.rs#L51) function which recursively extracts the coefficients and variables from the expressions.

### Reproduce
Default branch uses `CbcSolver`, test passes.
```shell
git clone https://github.com/carrascomj/kair.git
cd kair
cargo test
```
Default branch uses `NativeCbcSolver` for tests, test fails (a different solution is returned).
```shell
git clone -b run-native https://github.com/carrascomj/kair.git
cd kair
cargo test
```

**Comment by carrascomj** [comment]
This might interest @dginev (working for me now).

**Comment by dginev** [comment]
I guess it's good I waited! Thanks a lot for this work, the native interface is going to be quite great going forward.
