### ISSUE TITLE
minilp solver?

### ISSUE THREAD

**Issue by carrascomj** [jcavat/rust-lp-modeler#57]
Opening discussion: there is a native implementation of a LP solver in Rust: [minilp](https://github.com/ztlpn/minilp). Supporting it would provide

- a native experience, no external installation involved (glpk, cbc, etc.);
- an useful fallback for higher level crates that rely on `lp_modeler`; 
- yet another solver to maintain.

Would this be interesting for the crate?

**Comment by carrascomj** [comment]
Kindly pinging the author of minilp @ztlpn; maybe you find this interesting.

**Comment by jcavat** [comment]
It could be great. All contributions are welcome. Effectively, it would be more to maintain but it makes sense to promote such rust project. We just need to keep in mind to have the minimum of dependencies. If we can't, we could imagine integrating solver-modules independently from the core lib.

**Comment by carrascomj** [comment]
Great! We can make subcrates and/or put new solvers as a feature if needed, that would be very convenient. These are the ones from [minilp](https://github.com/ztlpn/minilp) (which are a bit outdated):
```
minilp v0.2.2 (/home/georg/GIT/minilp)
├── log v0.4.11
│   └── cfg-if v0.1.10
└── sprs v0.7.1
    ├── ndarray v0.13.1
    │   ├── matrixmultiply v0.2.3
    │   │   └── rawpointer v0.2.1
    │   ├── num-complex v0.2.4
    │   │   └── num-traits v0.2.14
    │   │       [build-dependencies]
    │   │       └── autocfg v1.0.1
    │   │   [build-dependencies]
    │   │   └── autocfg v1.0.1
    │   ├── num-integer v0.1.44
    │   │   └── num-traits v0.2.14 (*)
    │   │   [build-dependencies]
    │   │   └── autocfg v1.0.1
    │   ├── num-traits v0.2.14 (*)
    │   └── rawpointer v0.2.1
    ├── num-complex v0.2.4 (*)
    └── num-traits v0.1.43
        └── num-traits v0.2.14 (*)
```

**Comment by EdorianDark** [comment]
I would suggest to integrate it as a non default feature.
At least as long as it describes itself as "an early-stage project".
