### ISSUE TITLE
[Rust beginner] Easy way to construct expressions?

### ISSUE THREAD

**Issue by sbeyer** [jcavat/rust-lp-modeler#59]
I am looking for an "easy" way to construct more complex expressions.
From the examples I was expecting that something like
```rust
   let mut lhs = LpExpression::EmptyExpr;
   lhs += 5.0 * some_variable;
   for i in certain_i_indices {
      for j in certain_j_indices {
         lhs += some_coeff_collection[i][j] * some_variable_collection[i][j];
      }
   }
   problem += lhs.le(some_value);
```
would work, but it doesn't.

Can you provide some examples that are "easy" enough for that case?

**Comment by jcavat** [comment]
The `std::ops::AddAssign` (`+=`) is not defined for `LpExpression`. For now, you can replace your snippet by:
```rust
   let mut lhs = LpExpression::EmptyExpr;
   lhs = lhs + 5.0 * some_variable;
   for i in certain_i_indices {
      for j in certain_j_indices {
         lhs = lhs + some_coeff_collection[i][j] * some_variable_collection[i][j];
      }
   }
   problem += lhs.le(some_value);
```

PR are welcome :-)

**Comment by jcavat** [comment]
Or you can use `map`/`flat_map` and `sum`. You can get inspiration from [the example](https://github.com/jcavat/rust-lp-modeler/tree/master/examples/assignment.rs ).
```rust
    // Define Objective Function
    let obj_vec: Vec<LpExpression> = {
       vars.iter().map( |(&(m,w), bin)| {
           let &coef = compatibility_score.get(&(m, w)).unwrap();
           coef * bin
       } )
    }.collect();
    problem += obj_vec.sum();
```

in your case, something like:
```rust
    problem += (1..100).flat_map(|i| (1..100).map(|j| some_coeff_collection[i][j] * some_variable_collection[i][j])).collect::<Vec<LpExpression>>().sum().le(some_value);
```

More functional (or declarative), less procedural.

**Comment by sbeyer** [comment]
Thank you. I thought I had tried the `lhs = lhs + ...` variant but it seems I did not. It works!

I have seen the assignment problem example but I thought the presented functional solution is not really nicely adaptable to more complex situations (at least not in a readable way, but that's probably a matter of taste and habit).
