### ISSUE TITLE
no 64 bit support

### ISSUE THREAD

**Issue by RHavar** [jcavat/rust-lp-modeler#8]
The problem I'm trying to solve unfortunately doesn't fit in 32 bit numbers, and I'm getting:

```
the trait `std::ops::Mul<&lp_modeler::variables::LpBinary>` is not implemented for `i64`
```

Would be great to have 64 bit number support =)

**Comment by jcavat** [comment]
Hi, can you just give a small gist that I can quickly use to improve the lib ?

**Comment by jcavat** [comment]
Resolving the problem leads to undesired changes in the way we use the DSL. For exemple the obligation to write an expression like this `3i32 * a + 2*b` or `3i64 + 2*b`. One solution is to implement a generic LpProblem and fixing the type we need for all the problem or to use `isize` for integer. But for the float !??

**Comment by hellow554** [comment]
Any progress so far?
