### ISSUE TITLE
Weird issues modeling a problem

### ISSUE THREAD

**Issue by RHavar** [jcavat/rust-lp-modeler#9]
First of all: sorry for the shitty quality bug report.

I'm trying to model bitcoin coin selection with lp-modeler and have this which works completely as expected:

https://gist.github.com/RHavar/d2249af67e428befb966e4fcf7d95a17/92c7bb2bac02ec2147b2a1871be45a4391536cfb

(You can run it, and it also dump the `.lp` file.

Anyway, with a [minor change](https://gist.github.com/RHavar/d2249af67e428befb966e4fcf7d95a17/a95eb5a35aede5871f1835b37bbf938700ee81e5), it fails with:
signal 6:

And with [another minor change](https://gist.github.com/RHavar/d2249af67e428befb966e4fcf7d95a17/3d1654ee2b354a33ff9fa500b8c865f2702ca36d), it leads to bizarre results  (giving a decimal output for a binary problem) with weird names.

It's probably easiest to see by going to the gist:
https://gist.github.com/RHavar/d2249af67e428befb966e4fcf7d95a17/a95eb5a35aede5871f1835b37bbf938700ee81e5

And the original version is the one that works, and the next two changes are the weird results

**Comment by jcavat** [comment]
Ok, I will take a look soon. Can you give me your CBC version ? Did you try CBC with the exported lp file in command line ?

**Comment by jcavat** [comment]
Ok, I understand the problem. For now, this lib does not support distributive property. Example: `3 * (x1 + x2)` or `3 * (2 + x1)` doens't work yet. They should be written rather like this `3*x1 + 3*x2` and `6 * x1` respectively. 

Your program must be rewritten as this (I hope this is equivalent) :
```
extern crate lp_modeler;

fn main() {
    use lp_modeler::problem::{LpObjective, Problem, LpProblem};
    use lp_modeler::operations::{LpOperations};
    use lp_modeler::variables::{LpInteger, LpBinary, LpExpression, lp_sum};
    use lp_modeler::solvers::{SolverTrait, CbcSolver};
    use lp_modeler::problem::LpFileFormat;


    let input_coins: Vec<i32> = vec![150, 200, 300, 5000, 20323];
    let output_coins = vec![203];
    let fee_rate = 300;

    // constants

    let bytes_per_input = 92;
    let transaction_fixed_bytes = 12;
    let bytes_per_output = 34;


    // problem below

    let mut problem = LpProblem::new("Coin Selection", LpObjective::Minimize);



    let input_expressions: Vec<(LpBinary, LpExpression)> = input_coins.iter().enumerate().map(|(i,coin)| {
        let constraint_name = format!("contains{}", i);
        let ref constraint_variable = LpBinary::new(constraint_name.as_str());

        (constraint_variable.clone() , *coin * constraint_variable)
    }).collect();

    let input_amount_expressions = input_expressions.iter().map(|&(_,ref amount)| { amount }).collect();
    let input_count_expressions: Vec<LpExpression> = input_expressions.iter().map(|&(ref b,_)| { fee_rate*bytes_per_output*b.clone() }).collect();


    let ouput_sum = output_coins.iter().fold(0, |a,b| a + b);


    let input_count = lp_sum(&input_count_expressions);
    let transaction_bytes = input_count + fee_rate*transaction_fixed_bytes + fee_rate*bytes_per_output;
    let tx_fee_required = transaction_bytes;



    let must_be_ge_than_ouput = (lp_sum(&input_amount_expressions)).ge(ouput_sum + tx_fee_required);
    problem.add_constraints(&must_be_ge_than_ouput);

    // ...but let's try minimize it


    let input_count = lp_sum(&input_count_expressions);
    problem.add_objective_expression(&input_count);


    problem.write_lp("problem.lp");



    let solver = CbcSolver::new();

    match solver.run(&problem) {
        Ok((status, res)) => {
            println!("Status {:?}", status);
            for (name, value) in res.iter() {
                println!("value of {} = {}", name, value);
            }
        },
        Err(msg) => println!("{}", msg),
    }
}
```

**Comment by jcavat** [comment]
I create a new issue for distributive property: #10
